services:
  api:
    image: rondonqsar/api:dev
    build:
      context: .
      dockerfile: apps/api/dev.Dockerfile
    restart: always
    init: true
    command: ["pnpm", "--filter", "api", "start:dev"]
    env_file: .env
    depends_on:
      - redis
    ports:
      - "4000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - files:/files
      - /usr/local/bin/Mold2:/mold2/Mold2

  web:
    image: rondonqsar/web:dev
    build:
      context: .
      dockerfile: apps/web/dev.Dockerfile
    restart: always
    command: ["pnpm", "--filter", "web", "dev", "--", "--host"]
    ports:
      - "3000:5173"
    volumes:
      - ./:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    command: redis-server --maxmemory-policy noeviction
    restart: always
    volumes:
      - redis:/data

volumes:
  redis:
    driver: nfsvol
  files:
    driver: nfsvol
